### ISSUE TITLE
Expanded info in the main file

### ISSUE THREAD

**Issue by henryiii** [Crascit/DownloadProject#17]
I think it would be helpful to have the license and the URL to the GitHub repo in the file, so that it's easy to add the file(s) to a project's cmake folder.

**Comment by audiofanatic** [comment]
I think I originally didn't put the license info in the files themselves because I was trying to follow the pattern in other CMake files where the full license was specified in its own separate file. I see now though that CMake files still include at least some minimal copyright info and a link to the full license text. For example, most module files that come with CMake seem to start with text similar to the following:

```
# Distributed under the OSI-approved BSD 3-Clause License.  See accompanying
# file Copyright.txt or https://cmake.org/licensing for details.
```
I'd be willing to consider something similar, perhaps adding the following to the top of the `DownloadProject.cmake` and `DownloadProject.CMakeLists.cmake.in` files:

```
# Distributed under the OSI-approved MIT License.  See accompanying
# file LICENSE or https://github.com/Crascit/DownloadProject for details.
```

If this satisfies the licensing needs of the projects you are using these files in, feel free to submit the above as its own merge request and I should be able to accept it.
