### ISSUE TITLE
Discussion / Feature request: support for multi-config generators

### ISSUE THREAD

**Issue by MathiasMagnus** [Crascit/DownloadProject#31]
Would it be possible to support multi-config generators if the downloaded project supports installing multiple configurations side-by-side from a single configuration? Currently downloaded projects build using the default configuration and if it's not link-compatible with other configurations, one is in trouble.

**Comment by craigscott-crascit** [comment]
DownloadProject is no longer being developed. The [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) module, which has been part of CMake since 3.11, is a superior replacement. FetchContent evolved from DownloadProject originally.

It sounds like you may actually be looking for ExternalProject rather than FetchContent though. FetchContent adds source to your build for the same config as the main build. If you need to build for multiple configurations, you need separate builds, which ExternalProject would allow you to do. The down side is that it all happens at build time with ExternalProject, so you don't have direct access to any of its targets. You end up manually handling all the platform-specific names and locations of things your main build needs to refer to.

Another avenue that may be relevant is the Ninja Multi-Config generator. It has the unique capability of being able to build multiple configurations at once. It's more complicated and the capability isn't available for other multi-config generators (Xcode, Visual Studio), which will likely make it a non-starter for most scenarios. You can read up on it here:

https://cmake.org/cmake/help/latest/generator/Ninja%20Multi-Config.html#custom-commands

I suggest you move discussion to the [CMake forums](https://discourse.cmake.org) if you need further assistance with your scenario.
