### ISSUE TITLE
When does git sync happen?

### ISSUE THREAD

**Issue by JonasVautherin** [Crascit/DownloadProject#8]
It is not clear to me when the sync will happen. Right now, if I change `GIT_TAG`, then I need to remove my `build` directory and run cmake again. What if the git repository is updated? Do I need to manually clean my `build` from time to time to be sure I am on the latest version?

NOTE: the example only works for the "master" branch of "google-test" (they apparently changed the structure a little bit).

**Comment by audiofanatic** [comment]
Before GoogleTest shifted to github, its structure was different. When they moved to github, they combined gtest and gmock into the one git repository, resulting in the structure that is there now. All the tags in GoogleTest correspond to older releases which were from before the restructure, so they are probably not what you actually want to be using going forward, at least until a new release is made and a corresponding tag created for that new release. You could always use a specific git SHA1 until then if you want to lock down your build to a particular commit.

As for when the sync would happen, it should occur whenever you re-run the cmake stage. It won't happen just doing a build because the download check happens at cmake time (that's the whole point of the DownloadProject functionality).

You should not need to remove your build directory to get DownloadProject to check if an update is needed, just re-run cmake and don't use the UPDATE_DISCONNECTED option. You can disable that check with the UPDATE_DISCONNECTED option, as shown in the example. If you lock down to a specific git SHA1 or tag, then it makes sense to include this option, but if you want to follow a branch or master, then don't use UPDATE_DISCONNECTED.

**Comment by JonasVautherin** [comment]
Make perfect sense, thanks a lot!
